//------------------------------------------------------------------------------
// <autogenerated>
//     This code was generated by a CodeSmith Template.
//
//     DO NOT MODIFY contents of this file. Changes to this
//     file will be lost if the code is regenerated.
// </autogenerated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

namespace AdventureWorks.Data.Queries
{
    public static partial class AddressExtensions
    {

        /// <summary>
        /// Gets an instance by the primary key.
        /// </summary>
        public static AdventureWorks.Data.Entities.Address GetByKey(this System.Linq.IQueryable<AdventureWorks.Data.Entities.Address> queryable, int addressID)
        {
            var dbSet = queryable as System.Data.Entity.IDbSet<AdventureWorks.Data.Entities.Address>;
            if (dbSet != null)
                return dbSet.Find(addressID);
                
            return queryable.FirstOrDefault(a => a.AddressID == addressID);
        }

        /// <summary>
        /// Gets an instance by using a unique index.
        /// </summary>
        /// <returns>An instance of the entity or null if not found.</returns>
        public static AdventureWorks.Data.Entities.Address GetByRowguid(this IQueryable<AdventureWorks.Data.Entities.Address> queryable, System.Guid rowguid)
        {
            return queryable.FirstOrDefault(a => a.Rowguid == rowguid);
        }

        /// <summary>
        /// Gets an instance by using a unique index.
        /// </summary>
        /// <returns>An instance of the entity or null if not found.</returns>
        public static AdventureWorks.Data.Entities.Address GetByAddressLine1AddressLine2CityStateProvinceIDPostalCode(this IQueryable<AdventureWorks.Data.Entities.Address> queryable, string addressLine1, string addressLine2, string city, int stateProvinceID, string postalCode)
        {
            return queryable.FirstOrDefault(a => a.AddressLine1 == addressLine1
                && (a.AddressLine2 == addressLine2 || (addressLine2 == null && a.AddressLine2 == null))
                && a.City == city
                && a.StateProvinceID == stateProvinceID
                && a.PostalCode == postalCode);
        }

        public static IQueryable<AdventureWorks.Data.Entities.Address> ByStateProvinceID(this IQueryable<AdventureWorks.Data.Entities.Address> queryable, int stateProvinceID)
        {
            return queryable.Where(a => a.StateProvinceID == stateProvinceID);
        }
    }
}
