//------------------------------------------------------------------------------
// <autogenerated>
//     This code was generated by a CodeSmith Template.
//
//     DO NOT MODIFY contents of this file. Changes to this
//     file will be lost if the code is regenerated.
// </autogenerated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

namespace AdventureWorks.Data.Queries
{
    public static partial class AddressTypeExtensions
    {

        /// <summary>
        /// Gets an instance by the primary key.
        /// </summary>
        public static AdventureWorks.Data.Entities.AddressType GetByKey(this System.Linq.IQueryable<AdventureWorks.Data.Entities.AddressType> queryable, int addressTypeID)
        {
            var dbSet = queryable as System.Data.Entity.IDbSet<AdventureWorks.Data.Entities.AddressType>;
            if (dbSet != null)
                return dbSet.Find(addressTypeID);
                
            return queryable.FirstOrDefault(a => a.AddressTypeID == addressTypeID);
        }

        /// <summary>
        /// Gets an instance by using a unique index.
        /// </summary>
        /// <returns>An instance of the entity or null if not found.</returns>
        public static AdventureWorks.Data.Entities.AddressType GetByName(this IQueryable<AdventureWorks.Data.Entities.AddressType> queryable, string name)
        {
            return queryable.FirstOrDefault(a => a.Name == name);
        }

        /// <summary>
        /// Gets an instance by using a unique index.
        /// </summary>
        /// <returns>An instance of the entity or null if not found.</returns>
        public static AdventureWorks.Data.Entities.AddressType GetByRowguid(this IQueryable<AdventureWorks.Data.Entities.AddressType> queryable, System.Guid rowguid)
        {
            return queryable.FirstOrDefault(a => a.Rowguid == rowguid);
        }
    }
}
