//------------------------------------------------------------------------------
// <autogenerated>
//     This code was generated by a CodeSmith Template.
//
//     DO NOT MODIFY contents of this file. Changes to this
//     file will be lost if the code is regenerated.
// </autogenerated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

namespace AdventureWorks.Data.Queries
{
    public static partial class AWBuildVersionExtensions
    {

        /// <summary>
        /// Gets an instance by the primary key.
        /// </summary>
        public static AdventureWorks.Data.Entities.AWBuildVersion GetByKey(this System.Linq.IQueryable<AdventureWorks.Data.Entities.AWBuildVersion> queryable, byte systemInformationID)
        {
            var dbSet = queryable as System.Data.Entity.IDbSet<AdventureWorks.Data.Entities.AWBuildVersion>;
            if (dbSet != null)
                return dbSet.Find(systemInformationID);
                
            return queryable.FirstOrDefault(a => a.SystemInformationID == systemInformationID);
        }
    }
}
