//------------------------------------------------------------------------------
// <autogenerated>
//     This code was generated by a CodeSmith Template.
//
//     DO NOT MODIFY contents of this file. Changes to this
//     file will be lost if the code is regenerated.
// </autogenerated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

namespace AdventureWorks.Data.Queries
{
    public static partial class ContactExtensions
    {

        /// <summary>
        /// Gets an instance by the primary key.
        /// </summary>
        public static AdventureWorks.Data.Entities.Contact GetByKey(this System.Linq.IQueryable<AdventureWorks.Data.Entities.Contact> queryable, int contactID)
        {
            var dbSet = queryable as System.Data.Entity.IDbSet<AdventureWorks.Data.Entities.Contact>;
            if (dbSet != null)
                return dbSet.Find(contactID);
                
            return queryable.FirstOrDefault(c => c.ContactID == contactID);
        }

        /// <summary>
        /// Gets an instance by using a unique index.
        /// </summary>
        /// <returns>An instance of the entity or null if not found.</returns>
        public static AdventureWorks.Data.Entities.Contact GetByRowguid(this IQueryable<AdventureWorks.Data.Entities.Contact> queryable, System.Guid rowguid)
        {
            return queryable.FirstOrDefault(c => c.Rowguid == rowguid);
        }

        public static IQueryable<AdventureWorks.Data.Entities.Contact> ByEmailAddress(this IQueryable<AdventureWorks.Data.Entities.Contact> queryable, string emailAddress)
        {
            return queryable.Where(c => (c.EmailAddress == emailAddress || (emailAddress == null && c.EmailAddress == null)));
        }

        public static IQueryable<AdventureWorks.Data.Entities.Contact> ByAdditionalContactInfo(this IQueryable<AdventureWorks.Data.Entities.Contact> queryable, string additionalContactInfo)
        {
            return queryable.Where(c => (c.AdditionalContactInfo == additionalContactInfo || (additionalContactInfo == null && c.AdditionalContactInfo == null)));
        }
    }
}

