//------------------------------------------------------------------------------
// <autogenerated>
//     This code was generated by a CodeSmith Template.
//
//     DO NOT MODIFY contents of this file. Changes to this
//     file will be lost if the code is regenerated.
// </autogenerated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

namespace AdventureWorks.Data.Queries
{
    public static partial class CustomerExtensions
    {

        /// <summary>
        /// Gets an instance by the primary key.
        /// </summary>
        public static AdventureWorks.Data.Entities.Customer GetByKey(this System.Linq.IQueryable<AdventureWorks.Data.Entities.Customer> queryable, int customerID)
        {
            var dbSet = queryable as System.Data.Entity.IDbSet<AdventureWorks.Data.Entities.Customer>;
            if (dbSet != null)
                return dbSet.Find(customerID);
                
            return queryable.FirstOrDefault(c => c.CustomerID == customerID);
        }

        /// <summary>
        /// Gets an instance by using a unique index.
        /// </summary>
        /// <returns>An instance of the entity or null if not found.</returns>
        public static AdventureWorks.Data.Entities.Customer GetByAccountNumber(this IQueryable<AdventureWorks.Data.Entities.Customer> queryable, string accountNumber)
        {
            return queryable.FirstOrDefault(c => c.AccountNumber == accountNumber);
        }

        /// <summary>
        /// Gets an instance by using a unique index.
        /// </summary>
        /// <returns>An instance of the entity or null if not found.</returns>
        public static AdventureWorks.Data.Entities.Customer GetByRowguid(this IQueryable<AdventureWorks.Data.Entities.Customer> queryable, System.Guid rowguid)
        {
            return queryable.FirstOrDefault(c => c.Rowguid == rowguid);
        }

        public static IQueryable<AdventureWorks.Data.Entities.Customer> ByTerritoryID(this IQueryable<AdventureWorks.Data.Entities.Customer> queryable, int? territoryID)
        {
            return queryable.Where(c => (c.TerritoryID == territoryID || (territoryID == null && c.TerritoryID == null)));
        }
    }
}

