//------------------------------------------------------------------------------
// <autogenerated>
//     This code was generated by a CodeSmith Template.
//
//     DO NOT MODIFY contents of this file. Changes to this
//     file will be lost if the code is regenerated.
// </autogenerated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

namespace AdventureWorks.Data.Queries
{
    public static partial class CustomerAddressExtensions
    {

        /// <summary>
        /// Gets an instance by the primary key.
        /// </summary>
        public static AdventureWorks.Data.Entities.CustomerAddress GetByKey(this System.Linq.IQueryable<AdventureWorks.Data.Entities.CustomerAddress> queryable, int customerID, int addressID)
        {
            var dbSet = queryable as System.Data.Entity.IDbSet<AdventureWorks.Data.Entities.CustomerAddress>;
            if (dbSet != null)
                return dbSet.Find(customerID, addressID);
                
            return queryable.FirstOrDefault(c => c.CustomerID == customerID
                && c.AddressID == addressID);
        }

        /// <summary>
        /// Gets an instance by using a unique index.
        /// </summary>
        /// <returns>An instance of the entity or null if not found.</returns>
        public static AdventureWorks.Data.Entities.CustomerAddress GetByRowguid(this IQueryable<AdventureWorks.Data.Entities.CustomerAddress> queryable, System.Guid rowguid)
        {
            return queryable.FirstOrDefault(c => c.Rowguid == rowguid);
        }

        public static IQueryable<AdventureWorks.Data.Entities.CustomerAddress> ByCustomerID(this IQueryable<AdventureWorks.Data.Entities.CustomerAddress> queryable, int customerID)
        {
            return queryable.Where(c => c.CustomerID == customerID);
        }

        public static IQueryable<AdventureWorks.Data.Entities.CustomerAddress> ByAddressID(this IQueryable<AdventureWorks.Data.Entities.CustomerAddress> queryable, int addressID)
        {
            return queryable.Where(c => c.AddressID == addressID);
        }

        public static IQueryable<AdventureWorks.Data.Entities.CustomerAddress> ByAddressTypeID(this IQueryable<AdventureWorks.Data.Entities.CustomerAddress> queryable, int addressTypeID)
        {
            return queryable.Where(c => c.AddressTypeID == addressTypeID);
        }
    }
}

