//------------------------------------------------------------------------------
// <autogenerated>
//     This code was generated by a CodeSmith Template.
//
//     DO NOT MODIFY contents of this file. Changes to this
//     file will be lost if the code is regenerated.
// </autogenerated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

namespace AdventureWorks.Data.Queries
{
    public static partial class DocumentExtensions
    {

        /// <summary>
        /// Gets an instance by the primary key.
        /// </summary>
        public static AdventureWorks.Data.Entities.Document GetByKey(this System.Linq.IQueryable<AdventureWorks.Data.Entities.Document> queryable, int documentID)
        {
            var dbSet = queryable as System.Data.Entity.IDbSet<AdventureWorks.Data.Entities.Document>;
            if (dbSet != null)
                return dbSet.Find(documentID);
                
            return queryable.FirstOrDefault(d => d.DocumentID == documentID);
        }

        /// <summary>
        /// Gets an instance by using a unique index.
        /// </summary>
        /// <returns>An instance of the entity or null if not found.</returns>
        public static AdventureWorks.Data.Entities.Document GetByFileNameRevision(this IQueryable<AdventureWorks.Data.Entities.Document> queryable, string fileName, string revision)
        {
            return queryable.FirstOrDefault(d => d.FileName == fileName
                && d.Revision == revision);
        }
    }
}
