//------------------------------------------------------------------------------
// <autogenerated>
//     This code was generated by a CodeSmith Template.
//
//     DO NOT MODIFY contents of this file. Changes to this
//     file will be lost if the code is regenerated.
// </autogenerated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

namespace AdventureWorks.Data.Queries
{
    public static partial class EmployeeExtensions
    {

        /// <summary>
        /// Gets an instance by the primary key.
        /// </summary>
        public static AdventureWorks.Data.Entities.Employee GetByKey(this System.Linq.IQueryable<AdventureWorks.Data.Entities.Employee> queryable, int employeeID)
        {
            var dbSet = queryable as System.Data.Entity.IDbSet<AdventureWorks.Data.Entities.Employee>;
            if (dbSet != null)
                return dbSet.Find(employeeID);
                
            return queryable.FirstOrDefault(e => e.EmployeeID == employeeID);
        }

        /// <summary>
        /// Gets an instance by using a unique index.
        /// </summary>
        /// <returns>An instance of the entity or null if not found.</returns>
        public static AdventureWorks.Data.Entities.Employee GetByLoginID(this IQueryable<AdventureWorks.Data.Entities.Employee> queryable, string loginID)
        {
            return queryable.FirstOrDefault(e => e.LoginID == loginID);
        }

        /// <summary>
        /// Gets an instance by using a unique index.
        /// </summary>
        /// <returns>An instance of the entity or null if not found.</returns>
        public static AdventureWorks.Data.Entities.Employee GetByNationalIDNumber(this IQueryable<AdventureWorks.Data.Entities.Employee> queryable, string nationalIDNumber)
        {
            return queryable.FirstOrDefault(e => e.NationalIDNumber == nationalIDNumber);
        }

        /// <summary>
        /// Gets an instance by using a unique index.
        /// </summary>
        /// <returns>An instance of the entity or null if not found.</returns>
        public static AdventureWorks.Data.Entities.Employee GetByRowguid(this IQueryable<AdventureWorks.Data.Entities.Employee> queryable, System.Guid rowguid)
        {
            return queryable.FirstOrDefault(e => e.Rowguid == rowguid);
        }

        public static IQueryable<AdventureWorks.Data.Entities.Employee> ByManagerID(this IQueryable<AdventureWorks.Data.Entities.Employee> queryable, int? managerID)
        {
            return queryable.Where(e => (e.ManagerID == managerID || (managerID == null && e.ManagerID == null)));
        }

        public static IQueryable<AdventureWorks.Data.Entities.Employee> ByContactID(this IQueryable<AdventureWorks.Data.Entities.Employee> queryable, int contactID)
        {
            return queryable.Where(e => e.ContactID == contactID);
        }
    }
}
