//------------------------------------------------------------------------------
// <autogenerated>
//     This code was generated by a CodeSmith Template.
//
//     DO NOT MODIFY contents of this file. Changes to this
//     file will be lost if the code is regenerated.
// </autogenerated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

namespace AdventureWorks.Data.Queries
{
    public static partial class EmployeePayHistoryExtensions
    {

        /// <summary>
        /// Gets an instance by the primary key.
        /// </summary>
        public static AdventureWorks.Data.Entities.EmployeePayHistory GetByKey(this System.Linq.IQueryable<AdventureWorks.Data.Entities.EmployeePayHistory> queryable, int employeeID, System.DateTime rateChangeDate)
        {
            var dbSet = queryable as System.Data.Entity.IDbSet<AdventureWorks.Data.Entities.EmployeePayHistory>;
            if (dbSet != null)
                return dbSet.Find(employeeID, rateChangeDate);
                
            return queryable.FirstOrDefault(e => e.EmployeeID == employeeID
                && e.RateChangeDate == rateChangeDate);
        }

        public static IQueryable<AdventureWorks.Data.Entities.EmployeePayHistory> ByEmployeeID(this IQueryable<AdventureWorks.Data.Entities.EmployeePayHistory> queryable, int employeeID)
        {
            return queryable.Where(e => e.EmployeeID == employeeID);
        }
    }
}
