//------------------------------------------------------------------------------
// <autogenerated>
//     This code was generated by a CodeSmith Template.
//
//     DO NOT MODIFY contents of this file. Changes to this
//     file will be lost if the code is regenerated.
// </autogenerated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

namespace AdventureWorks.Data.Queries
{
    public static partial class EmployeeDepartmentHistoryExtensions
    {

        /// <summary>
        /// Gets an instance by the primary key.
        /// </summary>
        public static AdventureWorks.Data.Entities.EmployeeDepartmentHistory GetByKey(this System.Linq.IQueryable<AdventureWorks.Data.Entities.EmployeeDepartmentHistory> queryable, int employeeID, System.DateTime startDate, short departmentID, byte shiftID)
        {
            var dbSet = queryable as System.Data.Entity.IDbSet<AdventureWorks.Data.Entities.EmployeeDepartmentHistory>;
            if (dbSet != null)
                return dbSet.Find(employeeID, startDate, departmentID, shiftID);
                
            return queryable.FirstOrDefault(e => e.EmployeeID == employeeID
                && e.StartDate == startDate
                && e.DepartmentID == departmentID
                && e.ShiftID == shiftID);
        }

        public static IQueryable<AdventureWorks.Data.Entities.EmployeeDepartmentHistory> ByDepartmentID(this IQueryable<AdventureWorks.Data.Entities.EmployeeDepartmentHistory> queryable, short departmentID)
        {
            return queryable.Where(e => e.DepartmentID == departmentID);
        }

        public static IQueryable<AdventureWorks.Data.Entities.EmployeeDepartmentHistory> ByShiftID(this IQueryable<AdventureWorks.Data.Entities.EmployeeDepartmentHistory> queryable, byte shiftID)
        {
            return queryable.Where(e => e.ShiftID == shiftID);
        }

        public static IQueryable<AdventureWorks.Data.Entities.EmployeeDepartmentHistory> ByEmployeeID(this IQueryable<AdventureWorks.Data.Entities.EmployeeDepartmentHistory> queryable, int employeeID)
        {
            return queryable.Where(e => e.EmployeeID == employeeID);
        }
    }
}
