//------------------------------------------------------------------------------
// <autogenerated>
//     This code was generated by a CodeSmith Template.
//
//     DO NOT MODIFY contents of this file. Changes to this
//     file will be lost if the code is regenerated.
// </autogenerated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

namespace AdventureWorks.Data.Queries
{
    public static partial class JobCandidateExtensions
    {

        /// <summary>
        /// Gets an instance by the primary key.
        /// </summary>
        public static AdventureWorks.Data.Entities.JobCandidate GetByKey(this System.Linq.IQueryable<AdventureWorks.Data.Entities.JobCandidate> queryable, int jobCandidateID)
        {
            var dbSet = queryable as System.Data.Entity.IDbSet<AdventureWorks.Data.Entities.JobCandidate>;
            if (dbSet != null)
                return dbSet.Find(jobCandidateID);
                
            return queryable.FirstOrDefault(j => j.JobCandidateID == jobCandidateID);
        }

        public static IQueryable<AdventureWorks.Data.Entities.JobCandidate> ByEmployeeID(this IQueryable<AdventureWorks.Data.Entities.JobCandidate> queryable, int? employeeID)
        {
            return queryable.Where(j => (j.EmployeeID == employeeID || (employeeID == null && j.EmployeeID == null)));
        }
    }
}

