//------------------------------------------------------------------------------
// <autogenerated>
//     This code was generated by a CodeSmith Template.
//
//     DO NOT MODIFY contents of this file. Changes to this
//     file will be lost if the code is regenerated.
// </autogenerated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

namespace AdventureWorks.Data.Queries
{
    public static partial class ProductSubcategoryExtensions
    {

        /// <summary>
        /// Gets an instance by the primary key.
        /// </summary>
        public static AdventureWorks.Data.Entities.ProductSubcategory GetByKey(this System.Linq.IQueryable<AdventureWorks.Data.Entities.ProductSubcategory> queryable, int productSubcategoryID)
        {
            var dbSet = queryable as System.Data.Entity.IDbSet<AdventureWorks.Data.Entities.ProductSubcategory>;
            if (dbSet != null)
                return dbSet.Find(productSubcategoryID);
                
            return queryable.FirstOrDefault(p => p.ProductSubcategoryID == productSubcategoryID);
        }

        /// <summary>
        /// Gets an instance by using a unique index.
        /// </summary>
        /// <returns>An instance of the entity or null if not found.</returns>
        public static AdventureWorks.Data.Entities.ProductSubcategory GetByName(this IQueryable<AdventureWorks.Data.Entities.ProductSubcategory> queryable, string name)
        {
            return queryable.FirstOrDefault(p => p.Name == name);
        }

        /// <summary>
        /// Gets an instance by using a unique index.
        /// </summary>
        /// <returns>An instance of the entity or null if not found.</returns>
        public static AdventureWorks.Data.Entities.ProductSubcategory GetByRowguid(this IQueryable<AdventureWorks.Data.Entities.ProductSubcategory> queryable, System.Guid rowguid)
        {
            return queryable.FirstOrDefault(p => p.Rowguid == rowguid);
        }

        public static IQueryable<AdventureWorks.Data.Entities.ProductSubcategory> ByProductCategoryID(this IQueryable<AdventureWorks.Data.Entities.ProductSubcategory> queryable, int productCategoryID)
        {
            return queryable.Where(p => p.ProductCategoryID == productCategoryID);
        }
    }
}

