//------------------------------------------------------------------------------
// <autogenerated>
//     This code was generated by a CodeSmith Template.
//
//     DO NOT MODIFY contents of this file. Changes to this
//     file will be lost if the code is regenerated.
// </autogenerated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

namespace AdventureWorks.Data.Queries
{
    public static partial class ProductCategoryExtensions
    {

        /// <summary>
        /// Gets an instance by the primary key.
        /// </summary>
        public static AdventureWorks.Data.Entities.ProductCategory GetByKey(this System.Linq.IQueryable<AdventureWorks.Data.Entities.ProductCategory> queryable, int productCategoryID)
        {
            var dbSet = queryable as System.Data.Entity.IDbSet<AdventureWorks.Data.Entities.ProductCategory>;
            if (dbSet != null)
                return dbSet.Find(productCategoryID);
                
            return queryable.FirstOrDefault(p => p.ProductCategoryID == productCategoryID);
        }

        /// <summary>
        /// Gets an instance by using a unique index.
        /// </summary>
        /// <returns>An instance of the entity or null if not found.</returns>
        public static AdventureWorks.Data.Entities.ProductCategory GetByName(this IQueryable<AdventureWorks.Data.Entities.ProductCategory> queryable, string name)
        {
            return queryable.FirstOrDefault(p => p.Name == name);
        }

        /// <summary>
        /// Gets an instance by using a unique index.
        /// </summary>
        /// <returns>An instance of the entity or null if not found.</returns>
        public static AdventureWorks.Data.Entities.ProductCategory GetByRowguid(this IQueryable<AdventureWorks.Data.Entities.ProductCategory> queryable, System.Guid rowguid)
        {
            return queryable.FirstOrDefault(p => p.Rowguid == rowguid);
        }
    }
}
