//------------------------------------------------------------------------------
// <autogenerated>
//     This code was generated by a CodeSmith Template.
//
//     DO NOT MODIFY contents of this file. Changes to this
//     file will be lost if the code is regenerated.
// </autogenerated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

namespace AdventureWorks.Data.Queries
{
    public static partial class PurchaseOrderDetailExtensions
    {

        /// <summary>
        /// Gets an instance by the primary key.
        /// </summary>
        public static AdventureWorks.Data.Entities.PurchaseOrderDetail GetByKey(this System.Linq.IQueryable<AdventureWorks.Data.Entities.PurchaseOrderDetail> queryable, int purchaseOrderID, int purchaseOrderDetailID)
        {
            var dbSet = queryable as System.Data.Entity.IDbSet<AdventureWorks.Data.Entities.PurchaseOrderDetail>;
            if (dbSet != null)
                return dbSet.Find(purchaseOrderID, purchaseOrderDetailID);
                
            return queryable.FirstOrDefault(p => p.PurchaseOrderID == purchaseOrderID
                && p.PurchaseOrderDetailID == purchaseOrderDetailID);
        }

        public static IQueryable<AdventureWorks.Data.Entities.PurchaseOrderDetail> ByProductID(this IQueryable<AdventureWorks.Data.Entities.PurchaseOrderDetail> queryable, int productID)
        {
            return queryable.Where(p => p.ProductID == productID);
        }

        public static IQueryable<AdventureWorks.Data.Entities.PurchaseOrderDetail> ByPurchaseOrderID(this IQueryable<AdventureWorks.Data.Entities.PurchaseOrderDetail> queryable, int purchaseOrderID)
        {
            return queryable.Where(p => p.PurchaseOrderID == purchaseOrderID);
        }
    }
}

