//------------------------------------------------------------------------------
// <autogenerated>
//     This code was generated by a CodeSmith Template.
//
//     DO NOT MODIFY contents of this file. Changes to this
//     file will be lost if the code is regenerated.
// </autogenerated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

namespace AdventureWorks.Data.Queries
{
    public static partial class SalesTaxRateExtensions
    {

        /// <summary>
        /// Gets an instance by the primary key.
        /// </summary>
        public static AdventureWorks.Data.Entities.SalesTaxRate GetByKey(this System.Linq.IQueryable<AdventureWorks.Data.Entities.SalesTaxRate> queryable, int salesTaxRateID)
        {
            var dbSet = queryable as System.Data.Entity.IDbSet<AdventureWorks.Data.Entities.SalesTaxRate>;
            if (dbSet != null)
                return dbSet.Find(salesTaxRateID);
                
            return queryable.FirstOrDefault(s => s.SalesTaxRateID == salesTaxRateID);
        }

        /// <summary>
        /// Gets an instance by using a unique index.
        /// </summary>
        /// <returns>An instance of the entity or null if not found.</returns>
        public static AdventureWorks.Data.Entities.SalesTaxRate GetByRowguid(this IQueryable<AdventureWorks.Data.Entities.SalesTaxRate> queryable, System.Guid rowguid)
        {
            return queryable.FirstOrDefault(s => s.Rowguid == rowguid);
        }

        /// <summary>
        /// Gets an instance by using a unique index.
        /// </summary>
        /// <returns>An instance of the entity or null if not found.</returns>
        public static AdventureWorks.Data.Entities.SalesTaxRate GetByStateProvinceIDTaxType(this IQueryable<AdventureWorks.Data.Entities.SalesTaxRate> queryable, int stateProvinceID, byte taxType)
        {
            return queryable.FirstOrDefault(s => s.StateProvinceID == stateProvinceID
                && s.TaxType == taxType);
        }

        public static IQueryable<AdventureWorks.Data.Entities.SalesTaxRate> ByStateProvinceID(this IQueryable<AdventureWorks.Data.Entities.SalesTaxRate> queryable, int stateProvinceID)
        {
            return queryable.Where(s => s.StateProvinceID == stateProvinceID);
        }
    }
}
