//------------------------------------------------------------------------------
// <autogenerated>
//     This code was generated by a CodeSmith Template.
//
//     DO NOT MODIFY contents of this file. Changes to this
//     file will be lost if the code is regenerated.
// </autogenerated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

namespace AdventureWorks.Data.Queries
{
    public static partial class SalesOrderDetailExtensions
    {

        /// <summary>
        /// Gets an instance by the primary key.
        /// </summary>
        public static AdventureWorks.Data.Entities.SalesOrderDetail GetByKey(this System.Linq.IQueryable<AdventureWorks.Data.Entities.SalesOrderDetail> queryable, int salesOrderID, int salesOrderDetailID)
        {
            var dbSet = queryable as System.Data.Entity.IDbSet<AdventureWorks.Data.Entities.SalesOrderDetail>;
            if (dbSet != null)
                return dbSet.Find(salesOrderID, salesOrderDetailID);
                
            return queryable.FirstOrDefault(s => s.SalesOrderID == salesOrderID
                && s.SalesOrderDetailID == salesOrderDetailID);
        }

        /// <summary>
        /// Gets an instance by using a unique index.
        /// </summary>
        /// <returns>An instance of the entity or null if not found.</returns>
        public static AdventureWorks.Data.Entities.SalesOrderDetail GetByRowguid(this IQueryable<AdventureWorks.Data.Entities.SalesOrderDetail> queryable, System.Guid rowguid)
        {
            return queryable.FirstOrDefault(s => s.Rowguid == rowguid);
        }

        public static IQueryable<AdventureWorks.Data.Entities.SalesOrderDetail> ByProductID(this IQueryable<AdventureWorks.Data.Entities.SalesOrderDetail> queryable, int productID)
        {
            return queryable.Where(s => s.ProductID == productID);
        }

        public static IQueryable<AdventureWorks.Data.Entities.SalesOrderDetail> BySalesOrderID(this IQueryable<AdventureWorks.Data.Entities.SalesOrderDetail> queryable, int salesOrderID)
        {
            return queryable.Where(s => s.SalesOrderID == salesOrderID);
        }

        public static IQueryable<AdventureWorks.Data.Entities.SalesOrderDetail> BySpecialOfferID(this IQueryable<AdventureWorks.Data.Entities.SalesOrderDetail> queryable, int specialOfferID)
        {
            return queryable.Where(s => s.SpecialOfferID == specialOfferID);
        }
    }
}
