//------------------------------------------------------------------------------
// <autogenerated>
//     This code was generated by a CodeSmith Template.
//
//     DO NOT MODIFY contents of this file. Changes to this
//     file will be lost if the code is regenerated.
// </autogenerated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

namespace AdventureWorks.Data.Queries
{
    public static partial class SalesReasonExtensions
    {

        /// <summary>
        /// Gets an instance by the primary key.
        /// </summary>
        public static AdventureWorks.Data.Entities.SalesReason GetByKey(this System.Linq.IQueryable<AdventureWorks.Data.Entities.SalesReason> queryable, int salesReasonID)
        {
            var dbSet = queryable as System.Data.Entity.IDbSet<AdventureWorks.Data.Entities.SalesReason>;
            if (dbSet != null)
                return dbSet.Find(salesReasonID);
                
            return queryable.FirstOrDefault(s => s.SalesReasonID == salesReasonID);
        }
    }
}
