//------------------------------------------------------------------------------
// <autogenerated>
//     This code was generated by a CodeSmith Template.
//
//     DO NOT MODIFY contents of this file. Changes to this
//     file will be lost if the code is regenerated.
// </autogenerated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

namespace AdventureWorks.Data.Queries
{
    public static partial class SalesPersonQuotaHistoryExtensions
    {

        /// <summary>
        /// Gets an instance by the primary key.
        /// </summary>
        public static AdventureWorks.Data.Entities.SalesPersonQuotaHistory GetByKey(this System.Linq.IQueryable<AdventureWorks.Data.Entities.SalesPersonQuotaHistory> queryable, int salesPersonID, System.DateTime quotaDate)
        {
            var dbSet = queryable as System.Data.Entity.IDbSet<AdventureWorks.Data.Entities.SalesPersonQuotaHistory>;
            if (dbSet != null)
                return dbSet.Find(salesPersonID, quotaDate);
                
            return queryable.FirstOrDefault(s => s.SalesPersonID == salesPersonID
                && s.QuotaDate == quotaDate);
        }

        /// <summary>
        /// Gets an instance by using a unique index.
        /// </summary>
        /// <returns>An instance of the entity or null if not found.</returns>
        public static AdventureWorks.Data.Entities.SalesPersonQuotaHistory GetByRowguid(this IQueryable<AdventureWorks.Data.Entities.SalesPersonQuotaHistory> queryable, System.Guid rowguid)
        {
            return queryable.FirstOrDefault(s => s.Rowguid == rowguid);
        }

        public static IQueryable<AdventureWorks.Data.Entities.SalesPersonQuotaHistory> BySalesPersonID(this IQueryable<AdventureWorks.Data.Entities.SalesPersonQuotaHistory> queryable, int salesPersonID)
        {
            return queryable.Where(s => s.SalesPersonID == salesPersonID);
        }
    }
}

