//------------------------------------------------------------------------------
// <autogenerated>
//     This code was generated by a CodeSmith Template.
//
//     DO NOT MODIFY contents of this file. Changes to this
//     file will be lost if the code is regenerated.
// </autogenerated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

namespace AdventureWorks.Data.Queries
{
    public static partial class SalesTerritoryHistoryExtensions
    {

        /// <summary>
        /// Gets an instance by the primary key.
        /// </summary>
        public static AdventureWorks.Data.Entities.SalesTerritoryHistory GetByKey(this System.Linq.IQueryable<AdventureWorks.Data.Entities.SalesTerritoryHistory> queryable, int salesPersonID, System.DateTime startDate, int territoryID)
        {
            var dbSet = queryable as System.Data.Entity.IDbSet<AdventureWorks.Data.Entities.SalesTerritoryHistory>;
            if (dbSet != null)
                return dbSet.Find(salesPersonID, startDate, territoryID);
                
            return queryable.FirstOrDefault(s => s.SalesPersonID == salesPersonID
                && s.StartDate == startDate
                && s.TerritoryID == territoryID);
        }

        /// <summary>
        /// Gets an instance by using a unique index.
        /// </summary>
        /// <returns>An instance of the entity or null if not found.</returns>
        public static AdventureWorks.Data.Entities.SalesTerritoryHistory GetByRowguid(this IQueryable<AdventureWorks.Data.Entities.SalesTerritoryHistory> queryable, System.Guid rowguid)
        {
            return queryable.FirstOrDefault(s => s.Rowguid == rowguid);
        }

        public static IQueryable<AdventureWorks.Data.Entities.SalesTerritoryHistory> BySalesPersonID(this IQueryable<AdventureWorks.Data.Entities.SalesTerritoryHistory> queryable, int salesPersonID)
        {
            return queryable.Where(s => s.SalesPersonID == salesPersonID);
        }

        public static IQueryable<AdventureWorks.Data.Entities.SalesTerritoryHistory> ByTerritoryID(this IQueryable<AdventureWorks.Data.Entities.SalesTerritoryHistory> queryable, int territoryID)
        {
            return queryable.Where(s => s.TerritoryID == territoryID);
        }
    }
}

