//------------------------------------------------------------------------------
// <autogenerated>
//     This code was generated by a CodeSmith Template.
//
//     DO NOT MODIFY contents of this file. Changes to this
//     file will be lost if the code is regenerated.
// </autogenerated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

namespace AdventureWorks.Data.Queries
{
    public static partial class ShipMethodExtensions
    {

        /// <summary>
        /// Gets an instance by the primary key.
        /// </summary>
        public static AdventureWorks.Data.Entities.ShipMethod GetByKey(this System.Linq.IQueryable<AdventureWorks.Data.Entities.ShipMethod> queryable, int shipMethodID)
        {
            var dbSet = queryable as System.Data.Entity.IDbSet<AdventureWorks.Data.Entities.ShipMethod>;
            if (dbSet != null)
                return dbSet.Find(shipMethodID);
                
            return queryable.FirstOrDefault(s => s.ShipMethodID == shipMethodID);
        }

        /// <summary>
        /// Gets an instance by using a unique index.
        /// </summary>
        /// <returns>An instance of the entity or null if not found.</returns>
        public static AdventureWorks.Data.Entities.ShipMethod GetByName(this IQueryable<AdventureWorks.Data.Entities.ShipMethod> queryable, string name)
        {
            return queryable.FirstOrDefault(s => s.Name == name);
        }

        /// <summary>
        /// Gets an instance by using a unique index.
        /// </summary>
        /// <returns>An instance of the entity or null if not found.</returns>
        public static AdventureWorks.Data.Entities.ShipMethod GetByRowguid(this IQueryable<AdventureWorks.Data.Entities.ShipMethod> queryable, System.Guid rowguid)
        {
            return queryable.FirstOrDefault(s => s.Rowguid == rowguid);
        }
    }
}
