//------------------------------------------------------------------------------
// <autogenerated>
//     This code was generated by a CodeSmith Template.
//
//     DO NOT MODIFY contents of this file. Changes to this
//     file will be lost if the code is regenerated.
// </autogenerated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

namespace AdventureWorks.Data.Queries
{
    public static partial class ShoppingCartItemExtensions
    {

        /// <summary>
        /// Gets an instance by the primary key.
        /// </summary>
        public static AdventureWorks.Data.Entities.ShoppingCartItem GetByKey(this System.Linq.IQueryable<AdventureWorks.Data.Entities.ShoppingCartItem> queryable, int shoppingCartItemID)
        {
            var dbSet = queryable as System.Data.Entity.IDbSet<AdventureWorks.Data.Entities.ShoppingCartItem>;
            if (dbSet != null)
                return dbSet.Find(shoppingCartItemID);
                
            return queryable.FirstOrDefault(s => s.ShoppingCartItemID == shoppingCartItemID);
        }

        public static IQueryable<AdventureWorks.Data.Entities.ShoppingCartItem> ByShoppingCartIDProductID(this IQueryable<AdventureWorks.Data.Entities.ShoppingCartItem> queryable, string shoppingCartID, int productID)
        {
            return queryable.Where(s => s.ShoppingCartID == shoppingCartID
                && s.ProductID == productID);
        }

        public static IQueryable<AdventureWorks.Data.Entities.ShoppingCartItem> ByProductID(this IQueryable<AdventureWorks.Data.Entities.ShoppingCartItem> queryable, int productID)
        {
            return queryable.Where(s => s.ProductID == productID);
        }
    }
}

