//------------------------------------------------------------------------------
// <autogenerated>
//     This code was generated by a CodeSmith Template.
//
//     DO NOT MODIFY contents of this file. Changes to this
//     file will be lost if the code is regenerated.
// </autogenerated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

namespace AdventureWorks.Data.Queries
{
    public static partial class StoreContactExtensions
    {

        /// <summary>
        /// Gets an instance by the primary key.
        /// </summary>
        public static AdventureWorks.Data.Entities.StoreContact GetByKey(this System.Linq.IQueryable<AdventureWorks.Data.Entities.StoreContact> queryable, int customerID, int contactID)
        {
            var dbSet = queryable as System.Data.Entity.IDbSet<AdventureWorks.Data.Entities.StoreContact>;
            if (dbSet != null)
                return dbSet.Find(customerID, contactID);
                
            return queryable.FirstOrDefault(s => s.CustomerID == customerID
                && s.ContactID == contactID);
        }

        /// <summary>
        /// Gets an instance by using a unique index.
        /// </summary>
        /// <returns>An instance of the entity or null if not found.</returns>
        public static AdventureWorks.Data.Entities.StoreContact GetByRowguid(this IQueryable<AdventureWorks.Data.Entities.StoreContact> queryable, System.Guid rowguid)
        {
            return queryable.FirstOrDefault(s => s.Rowguid == rowguid);
        }

        public static IQueryable<AdventureWorks.Data.Entities.StoreContact> ByContactID(this IQueryable<AdventureWorks.Data.Entities.StoreContact> queryable, int contactID)
        {
            return queryable.Where(s => s.ContactID == contactID);
        }

        public static IQueryable<AdventureWorks.Data.Entities.StoreContact> ByContactTypeID(this IQueryable<AdventureWorks.Data.Entities.StoreContact> queryable, int contactTypeID)
        {
            return queryable.Where(s => s.ContactTypeID == contactTypeID);
        }

        public static IQueryable<AdventureWorks.Data.Entities.StoreContact> ByCustomerID(this IQueryable<AdventureWorks.Data.Entities.StoreContact> queryable, int customerID)
        {
            return queryable.Where(s => s.CustomerID == customerID);
        }
    }
}

