//------------------------------------------------------------------------------
// <autogenerated>
//     This code was generated by a CodeSmith Template.
//
//     DO NOT MODIFY contents of this file. Changes to this
//     file will be lost if the code is regenerated.
// </autogenerated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

namespace AdventureWorks.Data.Queries
{
    public static partial class StoreExtensions
    {

        /// <summary>
        /// Gets an instance by the primary key.
        /// </summary>
        public static AdventureWorks.Data.Entities.Store GetByKey(this System.Linq.IQueryable<AdventureWorks.Data.Entities.Store> queryable, int customerID)
        {
            var dbSet = queryable as System.Data.Entity.IDbSet<AdventureWorks.Data.Entities.Store>;
            if (dbSet != null)
                return dbSet.Find(customerID);
                
            return queryable.FirstOrDefault(s => s.CustomerID == customerID);
        }

        /// <summary>
        /// Gets an instance by using a unique index.
        /// </summary>
        /// <returns>An instance of the entity or null if not found.</returns>
        public static AdventureWorks.Data.Entities.Store GetByRowguid(this IQueryable<AdventureWorks.Data.Entities.Store> queryable, System.Guid rowguid)
        {
            return queryable.FirstOrDefault(s => s.Rowguid == rowguid);
        }

        public static IQueryable<AdventureWorks.Data.Entities.Store> BySalesPersonID(this IQueryable<AdventureWorks.Data.Entities.Store> queryable, int? salesPersonID)
        {
            return queryable.Where(s => (s.SalesPersonID == salesPersonID || (salesPersonID == null && s.SalesPersonID == null)));
        }

        public static IQueryable<AdventureWorks.Data.Entities.Store> ByDemographics(this IQueryable<AdventureWorks.Data.Entities.Store> queryable, string demographics)
        {
            return queryable.Where(s => (s.Demographics == demographics || (demographics == null && s.Demographics == null)));
        }
    }
}

