//------------------------------------------------------------------------------
// <autogenerated>
//     This code was generated by a CodeSmith Template.
//
//     DO NOT MODIFY contents of this file. Changes to this
//     file will be lost if the code is regenerated.
// </autogenerated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

namespace AdventureWorks.Data.Queries
{
    public static partial class VendorAddressExtensions
    {

        /// <summary>
        /// Gets an instance by the primary key.
        /// </summary>
        public static AdventureWorks.Data.Entities.VendorAddress GetByKey(this System.Linq.IQueryable<AdventureWorks.Data.Entities.VendorAddress> queryable, int vendorID, int addressID)
        {
            var dbSet = queryable as System.Data.Entity.IDbSet<AdventureWorks.Data.Entities.VendorAddress>;
            if (dbSet != null)
                return dbSet.Find(vendorID, addressID);
                
            return queryable.FirstOrDefault(v => v.VendorID == vendorID
                && v.AddressID == addressID);
        }

        public static IQueryable<AdventureWorks.Data.Entities.VendorAddress> ByAddressID(this IQueryable<AdventureWorks.Data.Entities.VendorAddress> queryable, int addressID)
        {
            return queryable.Where(v => v.AddressID == addressID);
        }

        public static IQueryable<AdventureWorks.Data.Entities.VendorAddress> ByVendorID(this IQueryable<AdventureWorks.Data.Entities.VendorAddress> queryable, int vendorID)
        {
            return queryable.Where(v => v.VendorID == vendorID);
        }

        public static IQueryable<AdventureWorks.Data.Entities.VendorAddress> ByAddressTypeID(this IQueryable<AdventureWorks.Data.Entities.VendorAddress> queryable, int addressTypeID)
        {
            return queryable.Where(v => v.AddressTypeID == addressTypeID);
        }
    }
}

