//------------------------------------------------------------------------------
// <autogenerated>
//     This code was generated by a CodeSmith Template.
//
//     DO NOT MODIFY contents of this file. Changes to this
//     file will be lost if the code is regenerated.
// </autogenerated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

namespace AdventureWorks.Data.Queries
{
    public static partial class WorkOrderRoutingExtensions
    {

        /// <summary>
        /// Gets an instance by the primary key.
        /// </summary>
        public static AdventureWorks.Data.Entities.WorkOrderRouting GetByKey(this System.Linq.IQueryable<AdventureWorks.Data.Entities.WorkOrderRouting> queryable, int workOrderID, int productID, short operationSequence)
        {
            var dbSet = queryable as System.Data.Entity.IDbSet<AdventureWorks.Data.Entities.WorkOrderRouting>;
            if (dbSet != null)
                return dbSet.Find(workOrderID, productID, operationSequence);
                
            return queryable.FirstOrDefault(w => w.WorkOrderID == workOrderID
                && w.ProductID == productID
                && w.OperationSequence == operationSequence);
        }

        public static IQueryable<AdventureWorks.Data.Entities.WorkOrderRouting> ByProductID(this IQueryable<AdventureWorks.Data.Entities.WorkOrderRouting> queryable, int productID)
        {
            return queryable.Where(w => w.ProductID == productID);
        }

        public static IQueryable<AdventureWorks.Data.Entities.WorkOrderRouting> ByWorkOrderID(this IQueryable<AdventureWorks.Data.Entities.WorkOrderRouting> queryable, int workOrderID)
        {
            return queryable.Where(w => w.WorkOrderID == workOrderID);
        }

        public static IQueryable<AdventureWorks.Data.Entities.WorkOrderRouting> ByLocationID(this IQueryable<AdventureWorks.Data.Entities.WorkOrderRouting> queryable, short locationID)
        {
            return queryable.Where(w => w.LocationID == locationID);
        }
    }
}

