//------------------------------------------------------------------------------
// <autogenerated>
//     This code was generated by a CodeSmith Template.
//
//     DO NOT MODIFY contents of this file. Changes to this
//     file will be lost if the code is regenerated.
// </autogenerated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Text;

namespace AdventureWorks.Data.Entities
{
    public partial class Address
    {
        public Address()
        {
            ModifiedDate = DateTime.Now;
            Employees = new List<Employee>();
            VendorAddresses = new List<VendorAddress>();
            CustomerAddresses = new List<CustomerAddress>();
            BillToSalesOrderHeaders = new List<SalesOrderHeader>();
            ShipToSalesOrderHeaders = new List<SalesOrderHeader>();
        }

        public int AddressID { get; set; }
        public string AddressLine1 { get; set; }
        public string AddressLine2 { get; set; }
        public string City { get; set; }
        public int StateProvinceID { get; set; }
        public string PostalCode { get; set; }
        public System.Guid Rowguid { get; set; }
        public System.DateTime ModifiedDate { get; set; }

        public virtual ICollection<Employee> Employees { get; set; }
        public virtual StateProvince StateProvince { get; set; }
        public virtual ICollection<VendorAddress> VendorAddresses { get; set; }
        public virtual ICollection<CustomerAddress> CustomerAddresses { get; set; }
        public virtual ICollection<SalesOrderHeader> BillToSalesOrderHeaders { get; set; }
        public virtual ICollection<SalesOrderHeader> ShipToSalesOrderHeaders { get; set; }
    }
}