//------------------------------------------------------------------------------
// <autogenerated>
//     This code was generated by a CodeSmith Template.
//
//     DO NOT MODIFY contents of this file. Changes to this
//     file will be lost if the code is regenerated.
// </autogenerated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Text;

namespace AdventureWorks.Data.Entities
{
    public partial class BillOfMaterials
    {
        public BillOfMaterials()
        {
            StartDate = DateTime.Now;
            PerAssemblyQty = (System.Decimal)1.00;
            ModifiedDate = DateTime.Now;
        }

        public int BillOfMaterialsID { get; set; }
        public int? ProductAssemblyID { get; set; }
        public int ComponentID { get; set; }
        public System.DateTime StartDate { get; set; }
        public System.DateTime? EndDate { get; set; }
        public string UnitMeasureCode { get; set; }
        public short BOMLevel { get; set; }
        public decimal PerAssemblyQty { get; set; }
        public System.DateTime ModifiedDate { get; set; }

        public virtual Product ComponentProduct { get; set; }
        public virtual Product AssemblyProduct { get; set; }
        public virtual UnitMeasure UnitMeasure { get; set; }
    }
}