//------------------------------------------------------------------------------
// <autogenerated>
//     This code was generated by a CodeSmith Template.
//
//     DO NOT MODIFY contents of this file. Changes to this
//     file will be lost if the code is regenerated.
// </autogenerated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Text;

namespace AdventureWorks.Data.Entities
{
    public partial class Currency
    {
        public Currency()
        {
            ModifiedDate = DateTime.Now;
            CountryRegions = new List<CountryRegion>();
            FromCurrencyRates = new List<CurrencyRate>();
            ToCurrencyRates = new List<CurrencyRate>();
        }

        public string CurrencyCode { get; set; }
        public string Name { get; set; }
        public System.DateTime ModifiedDate { get; set; }

        public virtual ICollection<CountryRegion> CountryRegions { get; set; }
        public virtual ICollection<CurrencyRate> FromCurrencyRates { get; set; }
        public virtual ICollection<CurrencyRate> ToCurrencyRates { get; set; }
    }
}