//------------------------------------------------------------------------------
// <autogenerated>
//     This code was generated by a CodeSmith Template.
//
//     DO NOT MODIFY contents of this file. Changes to this
//     file will be lost if the code is regenerated.
// </autogenerated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Text;

namespace AdventureWorks.Data.Entities
{
    public partial class Document
    {
        public Document()
        {
            ChangeNumber = 0;
            ModifiedDate = DateTime.Now;
            Products = new List<Product>();
        }

        public int DocumentID { get; set; }
        public string Title { get; set; }
        public string FileName { get; set; }
        public string FileExtension { get; set; }
        public string Revision { get; set; }
        public int ChangeNumber { get; set; }
        public byte Status { get; set; }
        public string DocumentSummary { get; set; }
        public System.Byte[] DocumentMember { get; set; }
        public System.DateTime ModifiedDate { get; set; }

        public virtual ICollection<Product> Products { get; set; }
    }
}