//------------------------------------------------------------------------------
// <autogenerated>
//     This code was generated by a CodeSmith Template.
//
//     DO NOT MODIFY contents of this file. Changes to this
//     file will be lost if the code is regenerated.
// </autogenerated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Text;

namespace AdventureWorks.Data.Entities
{
    public partial class UnitMeasure
    {
        public UnitMeasure()
        {
            BillOfMaterials = new List<BillOfMaterials>();
            SizeProducts = new List<Product>();
            WeightProducts = new List<Product>();
            ProductVendors = new List<ProductVendor>();
        }

        public string UnitMeasureCode { get; set; }
        public string Name { get; set; }
        public System.DateTime ModifiedDate { get; set; }

        public virtual ICollection<BillOfMaterials> BillOfMaterials { get; set; }
        public virtual ICollection<Product> SizeProducts { get; set; }
        public virtual ICollection<Product> WeightProducts { get; set; }
        public virtual ICollection<ProductVendor> ProductVendors { get; set; }
    }
}