//------------------------------------------------------------------------------
// <autogenerated>
//     This code was generated by a CodeSmith Template.
//
//     DO NOT MODIFY contents of this file. Changes to this
//     file will be lost if the code is regenerated.
// </autogenerated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace AdventureWorks.Data.Mapping
{
    public partial class CountryRegionMap
        : System.Data.Entity.ModelConfiguration.EntityTypeConfiguration<AdventureWorks.Data.Entities.CountryRegion>
    {
        public CountryRegionMap()
        {
            // table
            ToTable("CountryRegion", "Person");

            // keys
            HasKey(t => t.CountryRegionCode);

            // Properties
            Property(t => t.CountryRegionCode)
                .HasColumnName("CountryRegionCode")
                .HasMaxLength(3)
                .IsRequired();
            Property(t => t.Name)
                .HasColumnName("Name")
                .HasMaxLength(50)
                .IsRequired();
            Property(t => t.ModifiedDate)
                .HasColumnName("ModifiedDate")
                .IsRequired();

            // Relationships
            HasMany(t => t.Currencies)
                .WithMany(t => t.CountryRegions)
                .Map(m =>
                {
                    m.ToTable("CountryRegionCurrency", "Sales");
                    m.MapLeftKey("CountryRegionCode");
                    m.MapRightKey("CurrencyCode");
                });

            InitializeMapping();
        }
    }
}

