//------------------------------------------------------------------------------
// <autogenerated>
//     This code was generated by a CodeSmith Template.
//
//     DO NOT MODIFY contents of this file. Changes to this
//     file will be lost if the code is regenerated.
// </autogenerated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace AdventureWorks.Data.Mapping
{
    public partial class CreditCardMap
        : System.Data.Entity.ModelConfiguration.EntityTypeConfiguration<AdventureWorks.Data.Entities.CreditCard>
    {
        public CreditCardMap()
        {
            // table
            ToTable("CreditCard", "Sales");

            // keys
            HasKey(t => t.CreditCardID);

            // Properties
            Property(t => t.CreditCardID)
                .HasColumnName("CreditCardID")
                .HasDatabaseGeneratedOption(DatabaseGeneratedOption.Identity)
                .IsRequired();
            Property(t => t.CardType)
                .HasColumnName("CardType")
                .HasMaxLength(50)
                .IsRequired();
            Property(t => t.CardNumber)
                .HasColumnName("CardNumber")
                .HasMaxLength(25)
                .IsRequired();
            Property(t => t.ExpMonth)
                .HasColumnName("ExpMonth")
                .IsRequired();
            Property(t => t.ExpYear)
                .HasColumnName("ExpYear")
                .IsRequired();
            Property(t => t.ModifiedDate)
                .HasColumnName("ModifiedDate")
                .IsRequired();

            // Relationships

            InitializeMapping();
        }
    }
}

