//------------------------------------------------------------------------------
// <autogenerated>
//     This code was generated by a CodeSmith Template.
//
//     DO NOT MODIFY contents of this file. Changes to this
//     file will be lost if the code is regenerated.
// </autogenerated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace AdventureWorks.Data.Mapping
{
    public partial class CustomerAddressMap
        : System.Data.Entity.ModelConfiguration.EntityTypeConfiguration<AdventureWorks.Data.Entities.CustomerAddress>
    {
        public CustomerAddressMap()
        {
            // table
            ToTable("CustomerAddress", "Sales");

            // keys
            HasKey(t => new { t.CustomerID, t.AddressID });

            // Properties
            Property(t => t.CustomerID)
                .HasColumnName("CustomerID")
                .IsRequired();
            Property(t => t.AddressID)
                .HasColumnName("AddressID")
                .IsRequired();
            Property(t => t.AddressTypeID)
                .HasColumnName("AddressTypeID")
                .IsRequired();
            Property(t => t.Rowguid)
                .HasColumnName("rowguid")
                .IsRequired();
            Property(t => t.ModifiedDate)
                .HasColumnName("ModifiedDate")
                .IsRequired();

            // Relationships
            HasRequired(t => t.Address)
                .WithMany(t => t.CustomerAddresses)
                .HasForeignKey(d => d.AddressID)
                .WillCascadeOnDelete(false);
            HasRequired(t => t.AddressType)
                .WithMany(t => t.CustomerAddresses)
                .HasForeignKey(d => d.AddressTypeID)
                .WillCascadeOnDelete(false);
            HasRequired(t => t.Customer)
                .WithMany(t => t.CustomerAddresses)
                .HasForeignKey(d => d.CustomerID)
                .WillCascadeOnDelete(false);

            InitializeMapping();
        }
    }
}

