//------------------------------------------------------------------------------
// <autogenerated>
//     This code was generated by a CodeSmith Template.
//
//     DO NOT MODIFY contents of this file. Changes to this
//     file will be lost if the code is regenerated.
// </autogenerated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace AdventureWorks.Data.Mapping
{
    public partial class DatabaseLogMap
        : System.Data.Entity.ModelConfiguration.EntityTypeConfiguration<AdventureWorks.Data.Entities.DatabaseLog>
    {
        public DatabaseLogMap()
        {
            // table
            ToTable("DatabaseLog", "dbo");

            // keys
            HasKey(t => t.DatabaseLogID);

            // Properties
            Property(t => t.DatabaseLogID)
                .HasColumnName("DatabaseLogID")
                .HasDatabaseGeneratedOption(DatabaseGeneratedOption.Identity)
                .IsRequired();
            Property(t => t.PostTime)
                .HasColumnName("PostTime")
                .IsRequired();
            Property(t => t.DatabaseUser)
                .HasColumnName("DatabaseUser")
                .HasMaxLength(128)
                .IsRequired();
            Property(t => t.Event)
                .HasColumnName("Event")
                .HasMaxLength(128)
                .IsRequired();
            Property(t => t.Schema)
                .HasColumnName("Schema")
                .HasMaxLength(128)
                .IsOptional();
            Property(t => t.Object)
                .HasColumnName("Object")
                .HasMaxLength(128)
                .IsOptional();
            Property(t => t.Tsql)
                .HasColumnName("TSQL")
                .IsRequired();
            Property(t => t.XmlEvent)
                .HasColumnName("XmlEvent")
                .IsRequired();

            // Relationships

            InitializeMapping();
        }
    }
}

