//------------------------------------------------------------------------------
// <autogenerated>
//     This code was generated by a CodeSmith Template.
//
//     DO NOT MODIFY contents of this file. Changes to this
//     file will be lost if the code is regenerated.
// </autogenerated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace AdventureWorks.Data.Mapping
{
    public partial class EmployeeDepartmentHistoryMap
        : System.Data.Entity.ModelConfiguration.EntityTypeConfiguration<AdventureWorks.Data.Entities.EmployeeDepartmentHistory>
    {
        public EmployeeDepartmentHistoryMap()
        {
            // table
            ToTable("EmployeeDepartmentHistory", "HumanResources");

            // keys
            HasKey(t => new { t.EmployeeID, t.DepartmentID, t.ShiftID, t.StartDate });

            // Properties
            Property(t => t.EmployeeID)
                .HasColumnName("EmployeeID")
                .IsRequired();
            Property(t => t.DepartmentID)
                .HasColumnName("DepartmentID")
                .IsRequired();
            Property(t => t.ShiftID)
                .HasColumnName("ShiftID")
                .IsRequired();
            Property(t => t.StartDate)
                .HasColumnName("StartDate")
                .IsRequired();
            Property(t => t.EndDate)
                .HasColumnName("EndDate")
                .IsOptional();
            Property(t => t.ModifiedDate)
                .HasColumnName("ModifiedDate")
                .IsRequired();

            // Relationships
            HasRequired(t => t.Department)
                .WithMany(t => t.EmployeeDepartmentHistories)
                .HasForeignKey(d => d.DepartmentID)
                .WillCascadeOnDelete(false);
            HasRequired(t => t.Employee)
                .WithMany(t => t.EmployeeDepartmentHistories)
                .HasForeignKey(d => d.EmployeeID)
                .WillCascadeOnDelete(false);
            HasRequired(t => t.Shift)
                .WithMany(t => t.EmployeeDepartmentHistories)
                .HasForeignKey(d => d.ShiftID)
                .WillCascadeOnDelete(false);

            InitializeMapping();
        }
    }
}

