//------------------------------------------------------------------------------
// <autogenerated>
//     This code was generated by a CodeSmith Template.
//
//     DO NOT MODIFY contents of this file. Changes to this
//     file will be lost if the code is regenerated.
// </autogenerated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace AdventureWorks.Data.Mapping
{
    public partial class IllustrationMap
        : System.Data.Entity.ModelConfiguration.EntityTypeConfiguration<AdventureWorks.Data.Entities.Illustration>
    {
        public IllustrationMap()
        {
            // table
            ToTable("Illustration", "Production");

            // keys
            HasKey(t => t.IllustrationID);

            // Properties
            Property(t => t.IllustrationID)
                .HasColumnName("IllustrationID")
                .HasDatabaseGeneratedOption(DatabaseGeneratedOption.Identity)
                .IsRequired();
            Property(t => t.Diagram)
                .HasColumnName("Diagram")
                .IsOptional();
            Property(t => t.ModifiedDate)
                .HasColumnName("ModifiedDate")
                .IsRequired();

            // Relationships
            HasMany(t => t.ProductModels)
                .WithMany(t => t.Illustrations)
                .Map(m =>
                {
                    m.ToTable("ProductModelIllustration", "Production");
                    m.MapLeftKey("IllustrationID");
                    m.MapRightKey("ProductModelID");
                });

            InitializeMapping();
        }
    }
}
