//------------------------------------------------------------------------------
// <autogenerated>
//     This code was generated by a CodeSmith Template.
//
//     DO NOT MODIFY contents of this file. Changes to this
//     file will be lost if the code is regenerated.
// </autogenerated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace AdventureWorks.Data.Mapping
{
    public partial class IndividualMap
        : System.Data.Entity.ModelConfiguration.EntityTypeConfiguration<AdventureWorks.Data.Entities.Individual>
    {
        public IndividualMap()
        {
            // table
            ToTable("Individual", "Sales");

            // keys
            HasKey(t => t.CustomerID);

            // Properties
            Property(t => t.CustomerID)
                .HasColumnName("CustomerID")
                .HasDatabaseGeneratedOption(DatabaseGeneratedOption.None)
                .IsRequired();
            Property(t => t.ContactID)
                .HasColumnName("ContactID")
                .IsRequired();
            Property(t => t.Demographics)
                .HasColumnName("Demographics")
                .IsOptional();
            Property(t => t.ModifiedDate)
                .HasColumnName("ModifiedDate")
                .IsRequired();

            // Relationships
            HasRequired(t => t.Contact)
                .WithMany(t => t.Individuals)
                .HasForeignKey(d => d.ContactID)
                .WillCascadeOnDelete(false);
            HasRequired(t => t.Customer)
                .WithMany(t => t.Individuals)
                .HasForeignKey(d => d.CustomerID)
                .WillCascadeOnDelete(false);

            InitializeMapping();
        }
    }
}
