//------------------------------------------------------------------------------
// <autogenerated>
//     This code was generated by a CodeSmith Template.
//
//     DO NOT MODIFY contents of this file. Changes to this
//     file will be lost if the code is regenerated.
// </autogenerated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace AdventureWorks.Data.Mapping
{
    public partial class ProductInventoryMap
        : System.Data.Entity.ModelConfiguration.EntityTypeConfiguration<AdventureWorks.Data.Entities.ProductInventory>
    {
        public ProductInventoryMap()
        {
            // table
            ToTable("ProductInventory", "Production");

            // keys
            HasKey(t => new { t.ProductID, t.LocationID });

            // Properties
            Property(t => t.ProductID)
                .HasColumnName("ProductID")
                .IsRequired();
            Property(t => t.LocationID)
                .HasColumnName("LocationID")
                .IsRequired();
            Property(t => t.Shelf)
                .HasColumnName("Shelf")
                .HasMaxLength(10)
                .IsRequired();
            Property(t => t.Bin)
                .HasColumnName("Bin")
                .IsRequired();
            Property(t => t.Quantity)
                .HasColumnName("Quantity")
                .IsRequired();
            Property(t => t.Rowguid)
                .HasColumnName("rowguid")
                .IsRequired();
            Property(t => t.ModifiedDate)
                .HasColumnName("ModifiedDate")
                .IsRequired();

            // Relationships
            HasRequired(t => t.Location)
                .WithMany(t => t.ProductInventories)
                .HasForeignKey(d => d.LocationID)
                .WillCascadeOnDelete(false);
            HasRequired(t => t.Product)
                .WithMany(t => t.ProductInventories)
                .HasForeignKey(d => d.ProductID)
                .WillCascadeOnDelete(false);

            InitializeMapping();
        }
    }
}

