//------------------------------------------------------------------------------
// <autogenerated>
//     This code was generated by a CodeSmith Template.
//
//     DO NOT MODIFY contents of this file. Changes to this
//     file will be lost if the code is regenerated.
// </autogenerated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace AdventureWorks.Data.Mapping
{
    public partial class PurchaseOrderDetailMap
        : System.Data.Entity.ModelConfiguration.EntityTypeConfiguration<AdventureWorks.Data.Entities.PurchaseOrderDetail>
    {
        public PurchaseOrderDetailMap()
        {
            // table
            ToTable("PurchaseOrderDetail", "Purchasing");

            // keys
            HasKey(t => new { t.PurchaseOrderID, t.PurchaseOrderDetailID });

            // Properties
            Property(t => t.PurchaseOrderID)
                .HasColumnName("PurchaseOrderID")
                .HasDatabaseGeneratedOption(DatabaseGeneratedOption.None)
                .IsRequired();
            Property(t => t.PurchaseOrderDetailID)
                .HasColumnName("PurchaseOrderDetailID")
                .HasDatabaseGeneratedOption(DatabaseGeneratedOption.Identity)
                .IsRequired();
            Property(t => t.DueDate)
                .HasColumnName("DueDate")
                .IsRequired();
            Property(t => t.OrderQty)
                .HasColumnName("OrderQty")
                .IsRequired();
            Property(t => t.ProductID)
                .HasColumnName("ProductID")
                .IsRequired();
            Property(t => t.UnitPrice)
                .HasColumnName("UnitPrice")
                .HasPrecision(19, 4)
                .IsRequired();
            Property(t => t.LineTotal)
                .HasColumnName("LineTotal")
                .HasDatabaseGeneratedOption(DatabaseGeneratedOption.Computed)
                .HasPrecision(19, 4)
                .IsRequired();
            Property(t => t.ReceivedQty)
                .HasColumnName("ReceivedQty")
                .HasPrecision(8, 2)
                .IsRequired();
            Property(t => t.RejectedQty)
                .HasColumnName("RejectedQty")
                .HasPrecision(8, 2)
                .IsRequired();
            Property(t => t.StockedQty)
                .HasColumnName("StockedQty")
                .HasDatabaseGeneratedOption(DatabaseGeneratedOption.Computed)
                .HasPrecision(9, 2)
                .IsRequired();
            Property(t => t.ModifiedDate)
                .HasColumnName("ModifiedDate")
                .IsRequired();

            // Relationships
            HasRequired(t => t.Product)
                .WithMany(t => t.PurchaseOrderDetails)
                .HasForeignKey(d => d.ProductID)
                .WillCascadeOnDelete(false);
            HasRequired(t => t.PurchaseOrderHeader)
                .WithMany(t => t.PurchaseOrderDetails)
                .HasForeignKey(d => d.PurchaseOrderID)
                .WillCascadeOnDelete(false);

            InitializeMapping();
        }
    }
}
