//------------------------------------------------------------------------------
// <autogenerated>
//     This code was generated by a CodeSmith Template.
//
//     DO NOT MODIFY contents of this file. Changes to this
//     file will be lost if the code is regenerated.
// </autogenerated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace AdventureWorks.Data.Mapping
{
    public partial class SalesPersonMap
        : System.Data.Entity.ModelConfiguration.EntityTypeConfiguration<AdventureWorks.Data.Entities.SalesPerson>
    {
        public SalesPersonMap()
        {
            // table
            ToTable("SalesPerson", "Sales");

            // keys
            HasKey(t => t.SalesPersonID);

            // Properties
            Property(t => t.SalesPersonID)
                .HasColumnName("SalesPersonID")
                .IsRequired();
            Property(t => t.TerritoryID)
                .HasColumnName("TerritoryID")
                .IsOptional();
            Property(t => t.SalesQuota)
                .HasColumnName("SalesQuota")
                .HasPrecision(19, 4)
                .IsOptional();
            Property(t => t.Bonus)
                .HasColumnName("Bonus")
                .HasPrecision(19, 4)
                .IsRequired();
            Property(t => t.CommissionPct)
                .HasColumnName("CommissionPct")
                .HasPrecision(10, 4)
                .IsRequired();
            Property(t => t.SalesYTD)
                .HasColumnName("SalesYTD")
                .HasPrecision(19, 4)
                .IsRequired();
            Property(t => t.SalesLastYear)
                .HasColumnName("SalesLastYear")
                .HasPrecision(19, 4)
                .IsRequired();
            Property(t => t.Rowguid)
                .HasColumnName("rowguid")
                .IsRequired();
            Property(t => t.ModifiedDate)
                .HasColumnName("ModifiedDate")
                .IsRequired();

            // Relationships
            HasRequired(t => t.Employee)
                .WithOptional(t => t.SalesPerson)
                .WillCascadeOnDelete(false);
            HasOptional(t => t.SalesTerritory)
                .WithMany(t => t.SalesPeople)
                .HasForeignKey(d => d.TerritoryID)
                .WillCascadeOnDelete(false);

            InitializeMapping();
        }
    }
}

