//------------------------------------------------------------------------------
// <autogenerated>
//     This code was generated by a CodeSmith Template.
//
//     DO NOT MODIFY contents of this file. Changes to this
//     file will be lost if the code is regenerated.
// </autogenerated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace AdventureWorks.Data.Mapping
{
    public partial class SalesOrderDetailMap
        : System.Data.Entity.ModelConfiguration.EntityTypeConfiguration<AdventureWorks.Data.Entities.SalesOrderDetail>
    {
        public SalesOrderDetailMap()
        {
            // table
            ToTable("SalesOrderDetail", "Sales");

            // keys
            HasKey(t => new { t.SalesOrderID, t.SalesOrderDetailID });

            // Properties
            Property(t => t.SalesOrderID)
                .HasColumnName("SalesOrderID")
                .IsRequired();
            Property(t => t.SalesOrderDetailID)
                .HasColumnName("SalesOrderDetailID")
                .HasDatabaseGeneratedOption(DatabaseGeneratedOption.Identity)
                .IsRequired();
            Property(t => t.CarrierTrackingNumber)
                .HasColumnName("CarrierTrackingNumber")
                .HasMaxLength(25)
                .IsOptional();
            Property(t => t.OrderQty)
                .HasColumnName("OrderQty")
                .IsRequired();
            Property(t => t.ProductID)
                .HasColumnName("ProductID")
                .IsRequired();
            Property(t => t.SpecialOfferID)
                .HasColumnName("SpecialOfferID")
                .IsRequired();
            Property(t => t.UnitPrice)
                .HasColumnName("UnitPrice")
                .HasPrecision(19, 4)
                .IsRequired();
            Property(t => t.UnitPriceDiscount)
                .HasColumnName("UnitPriceDiscount")
                .HasPrecision(19, 4)
                .IsRequired();
            Property(t => t.LineTotal)
                .HasColumnName("LineTotal")
                .HasDatabaseGeneratedOption(DatabaseGeneratedOption.Computed)
                .HasPrecision(38, 6)
                .IsRequired();
            Property(t => t.Rowguid)
                .HasColumnName("rowguid")
                .IsRequired();
            Property(t => t.ModifiedDate)
                .HasColumnName("ModifiedDate")
                .IsRequired();

            // Relationships
            HasRequired(t => t.SalesOrderHeader)
                .WithMany(t => t.SalesOrderDetails)
                .HasForeignKey(d => d.SalesOrderID)
                .WillCascadeOnDelete(true);
            HasRequired(t => t.SpecialOfferProduct)
                .WithMany(t => t.SalesOrderDetails)
                .HasForeignKey(d => new { d.SpecialOfferID, d.ProductID })
                .WillCascadeOnDelete(false);

            InitializeMapping();
        }
    }
}

