//------------------------------------------------------------------------------
// <autogenerated>
//     This code was generated by a CodeSmith Template.
//
//     DO NOT MODIFY contents of this file. Changes to this
//     file will be lost if the code is regenerated.
// </autogenerated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace AdventureWorks.Data.Mapping
{
    public partial class SalesTerritoryMap
        : System.Data.Entity.ModelConfiguration.EntityTypeConfiguration<AdventureWorks.Data.Entities.SalesTerritory>
    {
        public SalesTerritoryMap()
        {
            // table
            ToTable("SalesTerritory", "Sales");

            // keys
            HasKey(t => t.TerritoryID);

            // Properties
            Property(t => t.TerritoryID)
                .HasColumnName("TerritoryID")
                .HasDatabaseGeneratedOption(DatabaseGeneratedOption.Identity)
                .IsRequired();
            Property(t => t.Name)
                .HasColumnName("Name")
                .HasMaxLength(50)
                .IsRequired();
            Property(t => t.CountryRegionCode)
                .HasColumnName("CountryRegionCode")
                .HasMaxLength(3)
                .IsRequired();
            Property(t => t.Group)
                .HasColumnName("Group")
                .HasMaxLength(50)
                .IsRequired();
            Property(t => t.SalesYTD)
                .HasColumnName("SalesYTD")
                .HasPrecision(19, 4)
                .IsRequired();
            Property(t => t.SalesLastYear)
                .HasColumnName("SalesLastYear")
                .HasPrecision(19, 4)
                .IsRequired();
            Property(t => t.CostYTD)
                .HasColumnName("CostYTD")
                .HasPrecision(19, 4)
                .IsRequired();
            Property(t => t.CostLastYear)
                .HasColumnName("CostLastYear")
                .HasPrecision(19, 4)
                .IsRequired();
            Property(t => t.Rowguid)
                .HasColumnName("rowguid")
                .IsRequired();
            Property(t => t.ModifiedDate)
                .HasColumnName("ModifiedDate")
                .IsRequired();

            // Relationships

            InitializeMapping();
        }
    }
}

