//------------------------------------------------------------------------------
// <autogenerated>
//     This code was generated by a CodeSmith Template.
//
//     DO NOT MODIFY contents of this file. Changes to this
//     file will be lost if the code is regenerated.
// </autogenerated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace AdventureWorks.Data.Mapping
{
    public partial class SalesPersonQuotaHistoryMap
        : System.Data.Entity.ModelConfiguration.EntityTypeConfiguration<AdventureWorks.Data.Entities.SalesPersonQuotaHistory>
    {
        public SalesPersonQuotaHistoryMap()
        {
            // table
            ToTable("SalesPersonQuotaHistory", "Sales");

            // keys
            HasKey(t => new { t.SalesPersonID, t.QuotaDate });

            // Properties
            Property(t => t.SalesPersonID)
                .HasColumnName("SalesPersonID")
                .HasDatabaseGeneratedOption(DatabaseGeneratedOption.None)
                .IsRequired();
            Property(t => t.QuotaDate)
                .HasColumnName("QuotaDate")
                .HasDatabaseGeneratedOption(DatabaseGeneratedOption.None)
                .IsRequired();
            Property(t => t.SalesQuota)
                .HasColumnName("SalesQuota")
                .HasPrecision(19, 4)
                .IsRequired();
            Property(t => t.Rowguid)
                .HasColumnName("rowguid")
                .IsRequired();
            Property(t => t.ModifiedDate)
                .HasColumnName("ModifiedDate")
                .IsRequired();

            // Relationships
            HasRequired(t => t.SalesPerson)
                .WithMany(t => t.SalesPersonQuotaHistories)
                .HasForeignKey(d => d.SalesPersonID)
                .WillCascadeOnDelete(false);

            InitializeMapping();
        }
    }
}
