//------------------------------------------------------------------------------
// <autogenerated>
//     This code was generated by a CodeSmith Template.
//
//     DO NOT MODIFY contents of this file. Changes to this
//     file will be lost if the code is regenerated.
// </autogenerated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace AdventureWorks.Data.Mapping
{
    public partial class ShipMethodMap
        : System.Data.Entity.ModelConfiguration.EntityTypeConfiguration<AdventureWorks.Data.Entities.ShipMethod>
    {
        public ShipMethodMap()
        {
            // table
            ToTable("ShipMethod", "Purchasing");

            // keys
            HasKey(t => t.ShipMethodID);

            // Properties
            Property(t => t.ShipMethodID)
                .HasColumnName("ShipMethodID")
                .HasDatabaseGeneratedOption(DatabaseGeneratedOption.Identity)
                .IsRequired();
            Property(t => t.Name)
                .HasColumnName("Name")
                .HasMaxLength(50)
                .IsRequired();
            Property(t => t.ShipBase)
                .HasColumnName("ShipBase")
                .HasPrecision(19, 4)
                .IsRequired();
            Property(t => t.ShipRate)
                .HasColumnName("ShipRate")
                .HasPrecision(19, 4)
                .IsRequired();
            Property(t => t.Rowguid)
                .HasColumnName("rowguid")
                .IsRequired();
            Property(t => t.ModifiedDate)
                .HasColumnName("ModifiedDate")
                .IsRequired();

            // Relationships

            InitializeMapping();
        }
    }
}
