//------------------------------------------------------------------------------
// <autogenerated>
//     This code was generated by a CodeSmith Template.
//
//     DO NOT MODIFY contents of this file. Changes to this
//     file will be lost if the code is regenerated.
// </autogenerated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace AdventureWorks.Data.Mapping
{
    public partial class ShoppingCartItemMap
        : System.Data.Entity.ModelConfiguration.EntityTypeConfiguration<AdventureWorks.Data.Entities.ShoppingCartItem>
    {
        public ShoppingCartItemMap()
        {
            // table
            ToTable("ShoppingCartItem", "Sales");

            // keys
            HasKey(t => t.ShoppingCartItemID);

            // Properties
            Property(t => t.ShoppingCartItemID)
                .HasColumnName("ShoppingCartItemID")
                .HasDatabaseGeneratedOption(DatabaseGeneratedOption.Identity)
                .IsRequired();
            Property(t => t.ShoppingCartID)
                .HasColumnName("ShoppingCartID")
                .HasMaxLength(50)
                .IsRequired();
            Property(t => t.Quantity)
                .HasColumnName("Quantity")
                .IsRequired();
            Property(t => t.ProductID)
                .HasColumnName("ProductID")
                .IsRequired();
            Property(t => t.DateCreated)
                .HasColumnName("DateCreated")
                .IsRequired();
            Property(t => t.ModifiedDate)
                .HasColumnName("ModifiedDate")
                .IsRequired();

            // Relationships
            HasRequired(t => t.Product)
                .WithMany(t => t.ShoppingCartItems)
                .HasForeignKey(d => d.ProductID)
                .WillCascadeOnDelete(false);

            InitializeMapping();
        }
    }
}

