//------------------------------------------------------------------------------
// <autogenerated>
//     This code was generated by a CodeSmith Template.
//
//     DO NOT MODIFY contents of this file. Changes to this
//     file will be lost if the code is regenerated.
// </autogenerated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace AdventureWorks.Data.Mapping
{
    public partial class StoreContactMap
        : System.Data.Entity.ModelConfiguration.EntityTypeConfiguration<AdventureWorks.Data.Entities.StoreContact>
    {
        public StoreContactMap()
        {
            // table
            ToTable("StoreContact", "Sales");

            // keys
            HasKey(t => new { t.CustomerID, t.ContactID });

            // Properties
            Property(t => t.CustomerID)
                .HasColumnName("CustomerID")
                .HasDatabaseGeneratedOption(DatabaseGeneratedOption.None)
                .IsRequired();
            Property(t => t.ContactID)
                .HasColumnName("ContactID")
                .HasDatabaseGeneratedOption(DatabaseGeneratedOption.None)
                .IsRequired();
            Property(t => t.ContactTypeID)
                .HasColumnName("ContactTypeID")
                .IsRequired();
            Property(t => t.Rowguid)
                .HasColumnName("rowguid")
                .IsRequired();
            Property(t => t.ModifiedDate)
                .HasColumnName("ModifiedDate")
                .IsRequired();

            // Relationships
            HasRequired(t => t.Contact)
                .WithMany(t => t.StoreContacts)
                .HasForeignKey(d => d.ContactID)
                .WillCascadeOnDelete(false);
            HasRequired(t => t.ContactType)
                .WithMany(t => t.StoreContacts)
                .HasForeignKey(d => d.ContactTypeID)
                .WillCascadeOnDelete(false);
            HasRequired(t => t.Store)
                .WithMany(t => t.StoreContacts)
                .HasForeignKey(d => d.CustomerID)
                .WillCascadeOnDelete(false);

            InitializeMapping();
        }
    }
}
